### ISSUE TITLE
How do i build it?

### ISSUE THREAD

**Issue by Noel3454565FNF** [dimaguy/3ds-httpd#2]
I really want to use it but idk how to build

**Comment by Linkdash2019** [comment]
There’s a prebuilt one here 👉 https://github.com/dimaguy/3ds-httpd/releases/tag/nightly

I assume to build it you need Devkitpro. After devkitpro is installed on your system open the source code in a terminal and run ‘make’

**Comment by Noel3454565FNF** [comment]
i know there is a prebuilt but i want to make my own thing with it, thanks you 👍
